### ISSUE TITLE
Something went Wrong issue faced while booking

### ISSUE THREAD

**Issue by abhishek170996** [sushrut111/cowin-automation-extn#17]
I tried to book via pin code but after trying with pin several time it shows something went wrong
after this issue you cannot do anything tried to login again it says wait for 180 sec .
If I get this error again will share video link or image.

**Comment by dAKsh-Mido** [comment]
wait dev would look to your query soon when he gets some time

**Comment by negi39** [comment]
![Screenshot_20210523_123900](https://user-images.githubusercontent.com/84657771/119251532-a455c280-bbc4-11eb-9619-114e404b439a.jpg)
Something went wrong

**Comment by negi39** [comment]
Everything is work perfectly. I think this is a last issue (something went wrong).
Please take a time but solve this issue.

**Comment by sushrut111** [comment]
This happens when you send too many requests to cowin portal within a short span of time. This cannot be avoided through the extension. All you can do is not use the "Enable Auto Refresh option". 
You can use some other [extension](https://chrome.google.com/webstore/detail/auto-reload-page/cggooibcfafefodnecpcbgiebbjjpnpb) to refresh page periodically:
