### ISSUE TITLE
Add an optional field to provide preferred vaccination centre names

### ISSUE THREAD

**Issue by kshitij-srv** [sushrut111/cowin-automation-extn#6]
The Pincode search on Cowin gives arbitrary results in some cases. In my case for example it shows one centre that is close and another that is too far. Other nearby centres are ignored in the result.
When searching by district, auto selection can sometimes result in selection of centres that are far away too.

To curb this issue, there could be an optional field where user can provide certain vaccination centre names exactly matching the preferred centre names in Cowin results (like state and district). If any of those centres has a slot available, it is given first preference, otherwise whatever is available is chosen.

This way one could try booking slots in vaccination centres that are more feasible for them.

**Comment by sushrut111** [comment]
Hi Kshitij, thank you for the feedback. Actually just now I created a release with features you asked for.
You can now add comma separated keywords in the form for preferred center and only those centers will be selected for booking.
This option, however, is not available for the pincode based search. 

With this option, you can basically get the slot with just a click of confirm button. 

I am keeping this issue open so that you can verify this works correctly.

This is the release: https://github.com/sushrut111/cowin-automation-extn/releases/tag/v2.1.0
Here are the instructions for installing extension from release: https://github.com/sushrut111/cowin-automation-extn/wiki/How-install-extension-manually-from-github-release--(Before-the-version-is-published-to-chrome-web-store)

I hope this helps.

**Comment by kshitij-srv** [comment]
> Hi Kshitij, thank you for the feedback. Actually just now I created a release with features you asked for.
> You can now add comma separated keywords in the form for preferred center and only those centers will be selected for booking.
> This option, however, is not available for the pincode based search.
> 
> With this option, you can basically get the slot with just a click of confirm button.
> 
> I am keeping this issue open so that you can verify this works correctly.
> 
> This is the release: https://github.com/sushrut111/cowin-automation-extn/releases/tag/v2.1.0
> Here are the instructions for installing extension from release: https://github.com/sushrut111/cowin-automation-extn/wiki/How-install-extension-manually-from-github-release--(Before-the-version-is-published-to-chrome-web-store)
> 
> I hope this helps.

Wow this is the fastest I have ever seen an issue being resolved! 🙂  Kudos for keeping up the great work.
I installed the latest release. Haven't been able to verify it yet. Will keep you updated 👍
